name: Linux Build CI

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
    
    - uses: actions/checkout@v3

    - name: Add i386 architecture
      run: dpkg --add-architecture i386

    - name: Update repository
      run: apt-get update
      
    - name: Install build dependencies
      run: apt-get install -qq -y wget unzip build-essential gcc-5-multilib g++-5-multilib libgcc1:i386
    
    - name: Update alternatives
      run: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 100 --slave /usr/bin/g++ g++ /usr/bin/g++-5
      
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Run build
      working-directory: ./SurfMod
      run: make

    - name: Tag & publish to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        VERSION=latest
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
