name: Linux Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Add i386 architecture
      run: dpkg --add-architecture i386
      
    - name: Update repository
      run: apt-get update

    - name: Install build dependencies
      run: apt-get install -qq -y wget unzip build-essential gcc-4.8-multilib g++-4.8-multilib libgcc1:i386
    
    - name: Update alternatives
      run: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8

    - name: Run build
      working-directory: ./SurfMod
      run: make
    
    - name: Move release file to publish
      run: |
        # Make Surf Mod path
        mkdir -p publish/addons/SurfMod/dlls

        # Move released file to dlls
        mv ./SurfMod/Release/SurfMod_mm.so publish/addons/SurfMod/dlls

        # Copy cstrike contents to publish dir
        cp -ar cstrike/. publish

    - name: Download metamod-r
      run: |
        # Get latest release version of metamod-r
        wget --quiet https://github.com/theAsmodai/metamod-r/releases/download/1.3.0.131/metamod-bin-1.3.0.131.zip

        # Unzip metamod library to metamod folder
        unzip -p metamod-bin*.zip addons/metamod/metamod_i386.so > publish/addons/metamod/metamod_i386.so

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: SurfMod-linux
        path: publish/*
